name: Build React App
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Create env file
      #   run: |
      #     touch .env
      #     echo REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_ENDPOINT }} >> .env
      #     cat .env

      - name: Npm Install
        run: |
          npm install

      - name: Npm Build
        run: |
          npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: "build"

      - name: Print AWS Info
        run: |
          echo "AWS_S3_BUCKET=${{ secrets.AWS_STAGING_BUCKET_NAME }}"
          echo "AWS_REGION=${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Verify Secrets
        run: |
          echo "Checking if secrets are accessible..."
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then echo "AWS_ACCESS_KEY_ID is not set"; exit 1; fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then echo "AWS_SECRET_ACCESS_KEY is not set"; exit 1; fi
          if [ -z "${{ secrets.AWS_STAGING_BUCKET_NAME }}" ]; then echo "AWS_STAGING_BUCKET_NAME is not set"; exit 1; fi
          if [ -z "${{ secrets.AWS_DEFAULT_REGION }}" ]; then echo "AWS_DEFAULT_REGION is not set"; exit 1; fi
          echo "All secrets are accessible."
